name: deye_solarman
description: >
  Dart implementation of the SolarmanV5 / Modbus RTU protocol used by
  Solarman-compatible data loggers on Deye hybrid solar inverters.
version: 1.0.0
homepage: https://github.com/Mhmdkh77/deye-solarman
repository: https://github.com/Mhmdkh77/deye-solarman

environment:
  sdk: '>=3.2.2 <4.0.0'
